<?php 
//Prepare Display options to fine tune the form presentation
//This is optional, your form can be rendered without any display options
$displayOptions = array(
    //The class attribute added to the form tag
    //'class'                 => 'my-form-class',
    'fieldsets'             => array(
        'fsOne'                 => array(
            //The class attribute added to the fieldset class
            //'class'             => 'my-fsOne-class',
            //Should the display legend be shown? (If this option is not defined, defaults to true.)
            'display_legend'        => true,
            'elements'              => array(
                'name'              => array(
                    'class'                 => 'span3',
                    'required'              => true,
                ),
				'path'              => array(
            		'class'                 => 'span3',
            		'required'              => true,
            	),
            ),
        )
   	)
);

$form           = $this->form;
$formType       = $this->formType;
$form->prepare();

if ($form->getMessages()):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">x</button>
        <strong>Invalid input!</strong>
        The form fields are not filled out correctly.
    </div>
<?php endif; ?>

<?php 
echo $this->formTwb($form, $formType, $displayOptions);
?>