<h1>List of Servers</h1>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="servers">
        <thead>
          <tr>
          	<th>Server #</th>
            <th>Host</th>
            <th>Port</th>
            <th>Default</th>            
            <th>Operation</th>
          </tr>
        </thead>
        <tbody>          
          
          <?php foreach($servers as $server) : ?>          
          	<tr class="gradeB">
          		<td><?php echo $server->sip_server_id; ?></td>
	            <td class="center"><?php echo $server->host; ?></td>
	            <td class="center"><?php echo $server->port; ?></td>
	            <td class="center"><?php if ($server->default_server == 'Y')
	            			echo '<span class="badge badge-success">Yes</span>';
						  else
	            			 echo '<span class="badge badge-important">No</span>'; ?></td>   
	                
	                
	            <td class="center"><a href="<?php echo $this->url("sipsvr", array('action' => 'edit', 
	            											'id'	=> $server->sip_server_id)); ?>">Edit</a> | 
	            	<a href="<?php echo $this->url("sipsvr", array('action' => 'delete', 
	            											'id'	=> $server->sip_server_id)); ?>">Delete</a> 	            	             
            <?php endforeach;?>
           </tr>		
		</tbody>
</table>


<script type="text/javascript" charset="utf-8">
	$('#servers').dataTable( {
        "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>"
    } );
	$.extend( $.fn.dataTableExt.oStdClasses, {
	    "sWrapper": "dataTables_wrapper form-inline"
	} );
</script>

<?php 



?>