<h1>Calls by Client <small><?php echo $this->client_id; ?></small></h1>
<br>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="calls">
        <thead>
          <tr>
          	<th>Call ID</th>
            <th>Confirmed</th>
            <th>Max Amount</th>
            <th>Consumed Amount</th>
            <th>Started at</th>
            <th>Client ID</th> 
            <th>Operation</th>
          </tr>
        </thead>        
                 
          <?php 
			if (!$this->zfcUserIdentity())
					return;
	          	 
			if (!$this->authenticatedUser()->isReady())
	          		$this->authenticatedUser()->loadFromDatabase($this->zfcUserIdentity()->getId());
          ?>
       </table>

<script type="text/javascript" charset="utf-8">    
          
	$('#calls').dataTable( {

		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "<?php echo $this->url("calls", array('action' => 'grid')); ?>",
                
		"aoColumns": [   
		              { sWidth: '25%', sClass: "center" },   
		              { sWidth: '15%', sClass: "center" },   
		              { sWidth: '15%', sClass: "center" },   
		              { sWidth: '15%', sClass: "center" },
		              { sWidth: '20%', sClass: "center" },
		              { "bVisible":    false },
		              { sWidth: '5%', sClass: "center" }
		          ] , 		
    } );

	$.fn.dataTableExt.oApi.fnStandingRedraw = function(oSettings) {
	    if(oSettings.oFeatures.bServerSide === false){
	        var before = oSettings._iDisplayStart;
	 
	        oSettings.oApi._fnReDraw(oSettings);
	 
	        // iDisplayStart has been reset to zero - so lets change it back
	        oSettings._iDisplayStart = before;
	        oSettings.oApi._fnCalculateEnd(oSettings);
	    }
	      
	    // draw the 'current' page
	    oSettings.oApi._fnDraw(oSettings);
	};

	setInterval(function() { reloadMainTable() }, 5000);
	
	function reloadMainTable(){
		var oTable = $('#calls').dataTable();
		
		oTable.fnStandingRedraw();
		
		//window.setInterval(reloadMainTable(), 3000);
	}
    
	$.extend( $.fn.dataTableExt.oStdClasses, {
	    "sWrapper": "dataTables_wrapper form-inline"
	} );

	function callInfo(callID)
	{
		$.ajax({
	        url: "/calls/callinfo",
	        data: { "cid": callID },
	        cache: false,
	        type: 'GET',
	        dataType: 'json',
	        contentType: "application/json;charset=utf-8",
	        success: function (data, textStatus, jqXHR) {	
	        	
						var info    = '<table>' +
								  '<tr>' + 
								  '<td><i class="icon-arrow-right"></i> Initial pulse:</td>' +
								  '<td><b>' +  data.initial_pulse + '</b></td>' +
								  '</tr>' +
								  '<tr>' + 
								  '<td><i class="icon-arrow-right"></i> Final pulse:</td>' +
								  '<td><b>' +  data.final_pulse + '</b></td>' +
								  '</tr>' +
								  '<tr>' + 
								  '<td><i class="icon-arrow-right"></i> Cost per Sec:</td>' +
								  '<td><b>' +  data.cost_per_second + '</b></td>' +
								  '</tr>' +
								  '</table>';
			        	        	
	                $('div.modal-body').html(info);
	                $('#myModal').modal('show');
	             },
	             /*
	        error: function (xhr, ajaxOptions, thrownError) {
	               var errorMessage = xhr.responseText;
	               //alert(errorMessage);
	               //$('div.modal-body').html('<b>asd</b>');
	               //$('#myModal').modal('show');
	        	}*/
	    });
	}

</script>
 
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Call Information</h3>
  </div>
  <div id="#callInfoBody" href="#callInfoBody" class="modal-body">
	
  </div>
  <div class="modal-footer">
    <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Close</button>   
  </div>
</div>