<?php 

//Prepare Display options to fine tune the form presentation
//This is optional, your form can be rendered without any display options
$displayOptions = array(
    //The class attribute added to the form tag
    //'class'                 => 'my-form-class',
    'fieldsets'             => array(
        'fsOne'                 => array(
            //The class attribute added to the fieldset class
            //'class'             => 'my-fsOne-class',
            //Should the display legend be shown? (If this option is not defined, defaults to true.)
            'display_legend'        => true,
            'elements'              => array(
                'username'              => array(
                    'class'                 => 'span3',
                    'required'              => true,
                ),
            	'display_name'              => array(
            		'class'                 => 'span3',
            		'required'              => false,
            	),            		               
                'email'  => array(
                		'class'                 => 'span3',
                		'required'              => false,
                ),
                'max_disk_quota'  => array(
                		'class'                 => 'span3',
                		'required'              => true,
                ),
                'permission_id'  => array(
                		'class'                 => 'span3',
                		'required'              => true,
                ),
                'directory_id'  => array(
                		'class'                 => 'span3',
                		'required'              => true,
                ),
            ),
        )
   	)
);

//Form object
$form           = $this->form;

$formType       = $this->formType;

$validData      = $this->validData;
$form->prepare();

if ($form->getMessages() || isset($this->error)):
?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">x</button>
        <strong>Invalid input!</strong>
        <?php if (isset($this->error)) echo $this->error; else echo 'The form fields are not filled out correctly.'?>
    </div>

<!--     <div class="alert alert-success">
        <button class="close" data-dismiss="alert" type="button">x</button>
        <strong>User created successfully</strong>        
    </div>    
 -->
<?php endif;

echo $this->formTwb($form, $formType, $displayOptions); 

?>