<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Controller\IndexController'                                                => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Module'                                                                    => __DIR__ . '/Module.php',    
	'Application\Navigation\Service\ApplicationNavigationFactory'						 	=> __DIR__ . '/src/Application/Navigation/Service/ApplicationNavigationFactory.php',
	'User\Controller\Plugin\AuthenticatedUser'												=> __DIR__ . '/../User/src/User/Controller/Plugin/AuthenticatedUser.php'
);