<div id="play" class="modal hide fade in" style="display: none;">  
<div class="modal-header">  
<a class="close" data-dismiss="modal" onClick="javascript: window.location= '<?php echo $this->url('recording'); ?>'">&times;</a>    
</div>  
<div class="modal-body">  
<h5>Playing <i><?php echo $this->file; ?></i></h5>  
<p>
<object type="application/x-shockwave-flash" data="/player/player_mp3_maxi.swf" width="100%" height="20">
     <param name="movie" value="/player/player_mp3_maxi.swf" />
     <param name="FlashVars" value="mp3=<?php echo $this->recording_file; ?>?autoload=1&autoplay=1&showvolume=1" />         
</object>
</p>       
</div>  
<div class="modal-footer">  
<a href="#" class="btn" data-dismiss="modal" onClick="javascript: window.location= '<?php echo $this->url('recording'); ?>'">Close</a>  
</div>  
</div>

<script type="text/javascript">
    $(window).load(function(){
        $('#play').modal('show');
    });
</script>
